### ISSUE TITLE
Error when trying to navigate to entity graphs

### ISSUE THREAD

**Issue by pjdvmalan** [burtbeckwith/grails-app-info-hibernate#2]
Hello,

Using Grails 2.2.1 I created a new test project.

When I navigate to

http://localhost:8080/test/adminManage/index > Hibernate > Entity Graphs

I get the following error:

| Loading Grails 2.2.1
| Configuring classpath.
| Environment set to development.....
| Packaging Grails application....
| Compiling 1 source files.....
| Running Grails application

Configuring Spring Security UI ...
... finished configuring Spring Security UI

Configuring Spring Security Core ...
... finished configuring Spring Security Core

| Server running. Browse to http://localhost:8080/test
| Error 2013-10-16 13:37:11,506 [http-bio-8080-exec-6] ERROR errors.GrailsExceptionResolver  - IOException occurred when processing request: [GET] /test/adminManage/hibernateEntityGraph
CreateProcess error=3, The system cannot find the path specified. Stacktrace follows:
Message: CreateProcess error=3, The system cannot find the path specified
    Line | Method
->>  188 | <init>                  in java.lang.ProcessImpl

---

|    132 | start                   in     ''
|   1021 | start . . . . . . . . . in java.lang.ProcessBuilder
|    615 | exec                    in java.lang.Runtime
|    448 | exec . . . . . . . . .  in     ''
|    345 | exec                    in     ''
|    121 | createImage . . . . . . in com.burtbeckwith.grails.plugins.appinfo.hibernate.GrailsDocExporter
|     88 | generateDot             in     ''
|     48 | doStart . . . . . . . . in     ''
|     39 | start                   in     ''
|    252 | doWithExporter . . . .  in grails.plugins.appinfo.hibernate.HibernateInfoService
|     43 | generateEntityGraphCmap in     ''
|    117 | hibernateEntityGraph .  in com.burtbeckwith.grails.plugins.appinfo.hibernate.HibernateControllerMixin
|     44 | doCall                  in com.burtbeckwith.grails.plugins.dynamiccontroller.ControllerMixinClosureSource$_doGetClosure_closure1
|    186 | doFilter . . . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter                in grails.plugin.cache.web.filter.AbstractFilter
|   1110 | runWorker . . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    603 | run                     in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . . . . . . in java.lang.Thread

Is there anything I am missing?

**Comment by burtbeckwith** [comment]
I updated the plugin page with this info - to view the Hibernate graphs you must have Graphviz ( http://www.graphviz.org/ ) installed and in your PATH.

**Comment by pjdvmalan** [comment]
Thank you!
